name: worksheet
description: "High-performance Flutter spreadsheet widget supporting large datasets, 10%-400% zoom, and GPU-optimized tile-based rendering."
version: 1.1.0
homepage: https://pub.dev/packages/worksheet
screenshots:
  - description: 'Worksheet logo'
    path: assets/worksheet.png
repository: https://github.com/sjhorn/worksheet
issue_tracker: https://github.com/sjhorn/worksheet/issues
topics:
  - spreadsheet
  - worksheet
  - excel
  - table
  - widget

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
