name: worksheet
version: 1.4.0

homepage: https://pub.dev/packages/worksheet
repository: https://github.com/sjhorn/worksheet
description: High-performance Flutter spreadsheet widget supporting large datasets, 10%-400% zoom, and GPU-optimized tile-based rendering.
screenshots:
  - description: 'Worksheet widget screenshot'
    path: assets/worksheet.png
topics:
  - spreadsheet
  - worksheet
  - excel
  - table
  - widget

issue_tracker: https://github.com/sjhorn/worksheet/issues
environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
